### ISSUE TITLE
Inconsistent names between chapter and map+individual languages for values of feature 36, associative plural

### ISSUE THREAD

**Issue by pauamma** [cldf-datasets/wals#101]
Chapter 36 (https://wals.info/chapter/36), section 5 lists the values as:
* Associative plural marker also used for additive plurals (blue)
* Special bound associative plural marker (red)
* Special non-bound associative plural marker (orange)
* Associative plural absent (white)

The map (https://wals.info/feature/36A) and descriptions of some languages at least use different names for some of those values:
* Unique affixal associative plural instead of Special bound associative plural marker (https://wals.info/valuesets/36A-hun)
* Unique periphrastic associative plural instead of Special non-bound associative plural marker (Tagalog, https://wals.info/valuesets/36A-tag)
* No associative plural instead of Associative plural absent (Lakota, https://wals.info/valuesets/36A-lkt)

Using the same names throughout would be more consistent and less confusing.

**Comment by xrotwang** [comment]
I agree that this is a bit confusing. All [WALS feature values](https://github.com/cldf-datasets/wals/blob/master/cldf/codes.csv) have two descriptions; a short one to be displayed where space matters, and a longer one for full clarity. Of course, this system only works when short and long descriptions can be matched to each other clearly.

Right now, WALS is considered a finished publication, though. So unless the authors of 36A propose a change of these descriptions, we won't touch them.
