### ISSUE TITLE
typo (?) in language name, missing glottocode and isocode

### ISSUE THREAD

**Issue by MarvinMainz** [cldf-datasets/wals#117]
The language under the wals language_id "cos" bears the name "Rumsien" and is given without glottocode or isocode.

It seems to be a typo for the Coastanoan language otherwise known as "Rumsen": https://glottolog.org/resource/languoid/id/rums1243

I haven't looked into it, so maybe the name variant is legit, but in any case adding the glottocode would be nice.

**Comment by xrotwang** [comment]
[Kroeber 1904](https://glottolog.org/resource/reference/id/57711) calls the language Rumsien.

**Comment by MarvinMainz** [comment]
As said, my main concern was that there is no glottocode or isocode given
