### ISSUE TITLE
errors in ch Gender Distinctions in Independent Personal Pronouns: French, Italian

### ISSUE THREAD

**Issue by jcbradfield** [cldf-datasets/wals#15]
The database lists French and Italian as having gender in the 3rd singular only. But of course they distinguish gender in the 3rd plural as well. I checked the cited reference for French to see if it had some strange way of thinking, but it doesn't: it explains the complex evolving nature of French pronouns from a gender system to an animacy+sex system, but it doesn't mention the plural pronouns at all, let alone say they behave differently.

**Comment by xrotwang** [comment]
Feature won't be changed anymore for archival reasons.
