### ISSUE TITLE
Incorrect glosses or wrong analysis for Dagaare example in Chapter 44

### ISSUE THREAD

**Issue by chokingyou** [cldf-datasets/wals#44]
Example (9) from Dagaare in [Chapter 44](http://wals.info/chapter/44) has glosses "HON"="honorific" and "NHON"="non-honorific", while in the text it is discussed as an example of "a human/non-human distinction only in the third person plural".

**Comment by chokingyou** [comment]
I still do not understand.
it is either the glosses which are incorrect, or the analysis in the main
text.

best wishes,
—Maksim

ср, 29 янв. 2020 г. в 14:03, Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
I just removed the explicit mention of "honorific" which appears on mouse-over in the chapter (and this fix is not online yet). Whether using `(N)HON` as gloss label for a human/non-human distinction is incorrect would be something the original author must answer.

**Comment by chokingyou** [comment]
I see.
thank you!

best wishes,
—Maksim

чт, 30 янв. 2020 г. в 09:39, Robert Forkel <notifications@github.com>:
