### ISSUE TITLE
Redupliation in Nandi

### ISSUE THREAD

**Issue by rmalouf** [cldf-datasets/wals#6]
The chapter on Nandi (https://wals.info/languoid/lect/wals_code_nan) cites Mutaka 1990 as a source attesting to productive reduplication.  I think that paper is actually about the unrelated language **Kinande** (https://wals.info/languoid/lect/wals_code_nde). As far as I know, reduplication in Nandi is not productive.

**Comment by xrotwang** [comment]
It entails moving this datapoint from Nandi to Kinande.
