### ISSUE TITLE
No Dzongkha?

### ISSUE THREAD

**Issue by EkiRahardian** [cldf-datasets/wals#77]
I can't find the entry for Dzongkha language spoken in Bhutan. I even search the ISO 639-3 name but can't find anything.

**Comment by chrzyki** [comment]
Hi,

Dzongkha (ISO 639-3 `dzo`, correct?) was not part of WALS' compilation (see details [here](https://wals.info/)) and hence is also not available in the CLDF version of the data.

**Comment by EkiRahardian** [comment]
Yes, that's what i meant, thank you for the respond!
