### ISSUE TITLE
Datatype mismatch between CodeTable and ValueTable

### ISSUE THREAD

**Issue by Anaphory** [cldf-datasets/wals#85]
The values in the ValueTable are described as strings.
https://github.com/cldf-datasets/wals/blob/6833b645a5f57c32616a1293564abe2cf89c4b8f/cldf/StructureDataset-metadata.json#L72-L79
Presumably this is because they can contain `?` entries, but those should be mapped to null values and not interfere with the data type otherwise.
On the other hand, the code table lists the corresponding entries as integer.
https://github.com/cldf-datasets/wals/blob/6833b645a5f57c32616a1293564abe2cf89c4b8f/cldf/StructureDataset-metadata.json#L249-L250
This is a problem when loading the data set using `pycldf` and assuming that the objects in the #value column can be looked up in the CodeTable Number column (which, by the way, has no propertyURL and no other well-defined sematics that would make this connection machine-inferrable).

**Comment by xrotwang** [comment]
But the proper way to lookup rows in `CodeTable` which correspond to a value is via the `codeReference` foreign key - and **not** by assuming that `ValueTable:Value` and `CodeTable:Number` should match. The `Number` column in `CodeTable` indeed does not have any CLDF specified semantics. In the WALS dataset it simply means that the labels used for the categorical variables happen to be integers - and thus may be ordered for display.

**Comment by LinguList** [comment]
@Anaphory: For an example of how this would be done in pycldf, see this 
recent blog post: https://calc.hypotheses.org/2670
